# Local development services.
#
# To activate this feature, follow the instructions at the top of the
# 'example.settings.local.php' file, which sits next to this file.
parameters:
  http.response.debug_cacheability_headers: false
  twig.config:
    debug: false
    cache: true
services:
  twig/intl-extra:
    class: \Twig\Extra\Intl\IntlExtension
    tags:
      - { name: twig.extension }
  cache.backend.null:
    class: Drupal\Core\Cache\NullBackendFactory
