# Override any general project config via a .lando.local.yml file
# See https://docs.lando.dev/core/v3/#override-file for details.
name: nidirect
recipe: drupal10
env_file:
  - .env
config:
  webroot: web
  php: '8.2'
  composer_version: '2.5.8'
  via: apache:2.4
  database: mariadb:10.5
  # https://docs.lando.dev/config/drupal9.html#using-drush
  # As of Drupal 9 and Drush 10 it is preferred you use a site-local install of Drush.
  # For that reason Lando will not globally install a version of Drush for Drupal 9 sites.
  drush: false
  # https://docs.lando.dev/config/drupal9.html#using-xdebug
  xdebug: 'debug'
  config:
    php: .lando/config/php.ini
    database: .lando/config/my.cnf
compose:
  - docker-compose.yml
services:
  appserver:
    scanner: false
    environment:
      # Set node compilation flag to allow arm64 and x86 chipset compilation.
      CPPFLAGS: "-DPNG_ARM_NEON_OPT=0"
      # node version set here will be used by the nvm installer script.
      NODE_VERSION: 14.21.3
    build_as_root:
      - /app/.lando/scripts/appserver_build.sh
    run:
      - touch ~/.bashrc
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
    overrides:
      environment:
        # Support debugging CLI with XDEBUG.
        # Ensure PHPStorm->Preferences->PHP->Servers->Name is set to appserver.
        PHP_IDE_CONFIG: "serverName=appserver"
        XDEBUG_SESSION_START: lando
        SIMPLETEST_BASE_URL: "http://nidirect.lndo.site"
        SIMPLETEST_DB: "sqlite://localhost//dev/shm/test.sqlite"
  redis:
    type: redis:5.0
    persist: true
    config:
        server: .lando/config/redis.conf
  solr:
    type: solr:8.11
    portforward: true
    core: default
    config:
      dir: .lando/config/solr/
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
tooling:
  node:
    service: appserver
  xdebug-on:
    service: appserver
    description: Enable xdebug
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root
  yarn:
    service: appserver
    cmd: yarn
  nightwatch:
    service: appserver
    description: "Run Nightwatch.js functional tests.\n\n
                  Usage:\n
                  > Run a specific test with tag\n
                  lando nightwatch --tag your-tag\n
                  > Run a single test suite file, relative to Drupal core location\n
                  lando nightwatch ../modules/custom/modulename/tests/src/Nightwatch/Tests/yourTestSuite.js\n
                  > Run all tests except Core\n
                  lando nightwatch --skiptags core\n"
    cmd: "yarn --cwd=/app/web/core test:nightwatch"
  phpunit:
    description: "Run PHPUnit tests. You can pass options, e.g. --group=nidirect, as you require"
    service: appserver
    cmd: cd /app/web/core && /app/vendor/bin/phpunit -c /app/web/core/phpunit.xml
  phpcs:
    description: Run PHPCS checks against all custom Drupal code, e.g. 'lando phpcs'
    service: appserver
    cmd: /app/phpcs.sh "/app" "/app/web/modules/origins /app/web/modules/custom /app/web/themes/custom"
  drck:
    description: Run drupal-check for Drupal 9 compatibility e.g. 'lando drck ./'
    service: appserver
    cmd: /app/vendor/bin/drupal-check
  drush:
    server: appserver
    cmd: /app/vendor/bin/drush -r /app/drupal/web
  imp:
    description: Import Configuration and Structure
    cmd:
      - appserver: /app/vendor/bin/drush -r /app/web cr -y && /app/vendor/bin/drush -r /app/web cim -y && /app/vendor/bin/drush -r /app/web ia --choice=safe
  devmode:
    service: appserver
    description: Clone all DoF development repositories
    cmd: "sh /app/.lando/scripts/setup-for-dev.sh"
    user: root
  basic-auth:
    service: appserver
    description: Enable basic authentication
    cmd: "sh /app/.lando/scripts/basic-auth.sh"
    user: root
