# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: 'nidirect'

# The runtime the application uses.
type: 'php:7.4'

dependencies:
  php:
    composer/composer: '^2'

runtime:
  # Enable the redis extension so Drupal can communicate with the Redis cache.
  extensions:
    - apcu
    - newrelic
    - redis

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `:`.
relationships:
  solr: 'solr:solr'
  redis: "redis:redis"
  #  For MariaDB, the endpoint does not change whether you used the mysql or mariadb service type.
  database: 'db:admin'

# The size of the persistent disk of the application (in MB).
disk: 30720

# The 'mounts' describe writable, persistent filesystem mounts in the application.
mounts:
  '/web/sites/default/files':
    source: local
    source_path: 'files'
  '/tmp':
    source: local
    source_path: 'tmp'
  '/private':
    source: local
    source_path: 'private'
  '/imports':
    source: local
    source_path: 'imports'
  '/.drush':
    source: local
    source_path: 'drush'
  '/drush-backups':
    source: local
    source_path: 'drush-backups'
  '/.console':
    source: local
    source_path: 'console'
  '/.filebeat':
    source: local
    source_path: 'filebeat'

# Configuration of the build of this application.
build:
  flavor: composer

# The hooks executed at various points in the lifecycle of the application.
hooks:
  build: |
    set -e
    if [ ! -z $LOGZ_CONFIG ]; then
      echo "Run filebeat install script"
      ./config/filebeat/scripts/install.sh
    fi
    echo "Run filebeat install script"
    bash config/filebeat/scripts/install.sh
    echo "Replace vanilla CKEditor config with a custom one to fix the click/drag bug with embedded entities"
    git clone https://github.com/dof-dss/ckeditor4-fix-widget-dnd.git
    rm -rf web/core/assets/vendor/ckeditor
    mv ckeditor4-fix-widget-dnd/build/ckeditor web/core/assets/vendor/ckeditor
    rm -rf ckeditor4-fix-widget-dnd
    echo "Install Platform CLI tool"
    curl -sS https://platform.sh/cli/installer | php
    echo "Update robots.txt with NIDirect customisations"
    cp -f web/robots_nidirect.txt web/robots.txt
  # The deploy hook runs after your application has been deployed and started.
  deploy: |
    set -e
    # Copy filebeat files to filebeat mount if its empty.
    if [ ! "$(ls -A .filebeat)" ]; then
      echo "Copy filebeat build to filebeat mount"
      cp -v -r config/filebeat/build/filebeat-8.0.0-linux-x86_64/* .filebeat/
      mkdir .filebeat/registry
    fi
    echo "Running filebeat"
    cd .filebeat
    ./filebeat run --once
    echo "Create 'Easy Google Analytics Counter' auth file"
    printf '%s\n' "$EGAC_GA_AUTH" > /app/private/easy_google_analytics_counter_auth.json
    php ./drush/platformsh_generate_drush_yml.php
    cd web
    # Rebuild caches, run db-updates and import config.
    drush -y cache-rebuild
    drush -y updatedb
    # General config import
    drush -y config-import
    # Final cache rebuild.
    drush -y cache-rebuild
# The configuration of app when it is exposed to the web.
web:
  # Specific parameters for different URL prefixes.
  locations:
    '/':
      # The folder from which to serve static assets, for this location.
      #
      # This is a filesystem path, relative to the application root.
      root: 'web'

      # How long to allow static assets from this location to be cached.
      #
      # Can be a time in seconds, or -1 for no caching. Times can be
      # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
      # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
      # 365 days).
      expires: 5m

      # Whether to forward disallowed and missing resources from this
      # location to the application.
      #
      # Can be true, false or a URI path string.
      passthru: '/index.php'

      # Deny access to static files in this location.
      allow: false

      # Rules for specific URI patterns.
      rules:
        # Allow access to common static files.
        '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
          allow: true
          expires: 2w
        '^/robots\.txt$':
          allow: true
        '^/sitemap\.xml$':
          allow: true
        '^\/themes\/custom\/.+\/favicons\/.+\.webmanifest$':
          allow: true
          expires: 2w

        # Deny direct access to configuration files.
        '^/sites/sites\.php$':
          scripts: false
        '^/sites/[^/]+/settings.*?\.php$':
          scripts: false

    '/sites/default/files':
      # Allow access to all files in the public files directory.
      allow: true
      expires: 1d
      passthru: '/index.php'
      root: 'web/sites/default/files'

      # Do not execute PHP scripts.
      scripts: false

      rules:
        # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
        '^/sites/default/files/(css|js)':
          expires: 2w
