#!/usr/bin/env bash

## NIDirect-owned DDEV command.
## Description: Launch a browser with Solr Admin
## Usage: solr-admin
## Example: "ddev solr-admin"

DDEV_SOLR_ADMIN_PORT=8983
DDEV_SOLR_ADMIN_HTTPS_PORT=8943

if [ ${DDEV_PRIMARY_URL%://*} = "http" ] || [ -n "${GITPOD_WORKSPACE_ID:-}" ] || [ "${CODESPACES:-}" = "true" ]; then
    ddev launch :$DDEV_SOLR_ADMIN_PORT
else
    ddev launch :$DDEV_SOLR_ADMIN_HTTPS_PORT
fi
