adding:
  configuration:
    query:
      command: '/usr/local/bin/mailpit sendmail -t --smtp-addr 127.0.0.1:1025 -t -i'
removing:
  configuration:
    query:
      command: '/usr/sbin/sendmail -t -i'
