scanner_mode: true
scanner_wholeword: true
scanner_regex: false
scanner_published: false
scanner_pathauto: false
scanner_language: all
enabled_content_types:
  'node:application': 'node:application'
  'node:article': 'node:article'
  'node:contact': 'node:contact'
  'node:embargoed_publication': 'node:embargoed_publication'
  'node:health_condition': 'node:health_condition'
  'node:news': 'node:news'
  'node:page': 'node:page'
  'node:publication': 'node:publication'
  'node:webform': 'node:webform'
fields_of_selected_content_type:
  'node:application:title': 'node:application:title'
  'node:application:body': 'node:application:body'
  'node:application:field_additional_info': 'node:application:field_additional_info'
  'node:application:field_teaser': 'node:application:field_teaser'
  'node:article:title': 'node:article:title'
  'node:article:body': 'node:article:body'
  'node:article:field_additional_info': 'node:article:field_additional_info'
  'node:article:field_teaser': 'node:article:field_teaser'
  'node:contact:title': 'node:contact:title'
  'node:contact:body': 'node:contact:body'
  'node:contact:field_contact_additional_info': 'node:contact:field_contact_additional_info'
  'node:contact:field_contact_hours': 'node:contact:field_contact_hours'
  'node:embargoed_publication:title': 'node:embargoed_publication:title'
  'node:embargoed_publication:body': 'node:embargoed_publication:body'
  'node:embargoed_publication:field_additional_info': 'node:embargoed_publication:field_additional_info'
  'node:health_condition:title': 'node:health_condition:title'
  'node:health_condition:body': 'node:health_condition:body'
  'node:health_condition:field_additional_info': 'node:health_condition:field_additional_info'
  'node:health_condition:field_teaser': 'node:health_condition:field_teaser'
  'node:news:title': 'node:news:title'
  'node:news:body': 'node:news:body'
  'node:news:field_teaser': 'node:news:field_teaser'
  'node:page:title': 'node:page:title'
  'node:page:body': 'node:page:body'
  'node:publication:title': 'node:publication:title'
  'node:publication:body': 'node:publication:body'
  'node:publication:field_additional_info': 'node:publication:field_additional_info'
  'node:webform:title': 'node:webform:title'
  'node:webform:body': 'node:webform:body'
  'node:webform:field_teaser': 'node:webform:field_teaser'
_core:
  default_config_hash: m3e3lR0iNbau3eUO2RZya6iS06zv02m1JJe8X-PZuhk
