<?php

/**
 * @file
 * Schema and update hooks for GP and GP Practice.
 */

use Drupal\field\Entity\FieldConfig;

/**
 * Remove Practice and Surgery fields from GP Practice.
 */
function nidirect_gp_update_10001() {
  if ($field = FieldConfig::loadByName('node', 'gp_practice', 'field_gp_practice_name')) {
    $field->delete();
  }

  if ($field = FieldConfig::loadByName('node', 'gp_practice', 'field_gp_surgery_name')) {
    $field->delete();
  }
}
