# Each route describes how an incoming URL is going to be processed by Platform.sh.
"https://{default}/":
  type: upstream
  upstream: "nidirect:http"
  cache:
    enabled: false

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"
