# Each route describes how an incoming URL is going to be processed by Platform.sh.
"https://{default}/":
  type: upstream
  upstream: "nidirect:http"
  cache:
    enabled: true
    headers: ['Accept', 'Accept-Language', 'X-Language-Locale']
    default_ttl: 3600
    # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"
