# Each route describes how an incoming URL is going to be processed by Platform.sh.
"https://{default}/":
  type: upstream
  upstream: "nidirect:http"
  cache:
    enabled: false
  redirects:
    paths:
      '^(.*/)index\.php/(.*)':
        to: https://{default}/$2
        regexp: true
        code: 301

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"
