#!/usr/bin/env bash

## Description: Run drupal-check locally to detect deprecated code and ensure future compliance.
## Usage: drupal-check
## Aliases: drck
## Example: "ddev <drupal-check|drck> web/modules/custom"
## HostWorkingDir: true

/var/www/html/vendor/bin/drupal-check $1
