#!/usr/bin/env bash

## Description: Execute local PHPCS static analysis checks.
## Usage: phpcs
## Example: "ddev phpcs"

/app/phpcs.sh "/var/www/html" "/var/www/html/web/modules/origins /var/www/html/web/modules/custom /var/www/html/web/themes/custom"
