services:
  solr:
    build:
      context: ./solr
      args:
        SOLR_BASE_IMAGE: solr:9.9
    container_name: ddev-${DDEV_SITENAME}-solr
    restart: "no"
    expose:
      - 8983
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    environment:
      VIRTUAL_HOST: solr.${DDEV_HOSTNAME}
      HTTP_EXPOSE: 8983:8983
      HTTPS_EXPOSE: 8943:8983
      SOLR_MODULES: extraction,langid,ltr,analysis-extras
    volumes:
      - solr:/var/solr
      - .:/mnt/ddev_config
      - ${DDEV_APPROOT}/.platform/solr_configsets/nidirect:/solr-configset:ro
    entrypoint:
      - bash
      - /mnt/ddev_config/solr/create-or-refresh-core.sh
    external_links:
      - ddev-router:${DDEV_SITENAME}.${DDEV_TLD}
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s localhost:8983/solr/"]

volumes:
  solr:
    name: ddev-${DDEV_SITENAME}_solr
