name: Schedule CI

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  trigger-ci:
    uses: dof-dss/webdev-ci/.github/workflows/dispatch-workflow.yml@WDT-154
    permissions:
      actions: write
      contents: read
    with:
      workflow_id: ci.yml
      ref: development
